language: java

jdk:
  - oraclejdk7

env:
  matrix:
    - AS=wildfly-8.x
    - AS=jboss-7.1.x
    - AS=jboss-6.1.x
    - AS=jboss-5.1.x
    - AS=jboss-4.2.x
    - AS=glassfish-4.x
    - AS=glassfish-4.x-ds
    - AS=glassfish-3.x
    - AS=glassfish-3.x-ds
    - AS=jetty-9.x
    - AS=jetty-8.x
    - AS=jetty-7.x
    - AS=tomcat-8.x
    - AS=tomcat-7.x
    - AS=tomcat-6.x
    #- AS=weblogic-12.1.x
    - AS=resin-4.x
    - AS=jonas-5.x
    # disabling geronimo-3.x - see  https://github.com/p6spy/p6spy/issues/189
    #- AS=geronimo-3.x
    - AS=geronimo-2.2.x
    - AS=geronimo-2.1.x
    
before_install:
 - "sudo apt-get update -qq"
 - groovy script/travis/generateMavenSettingsForIT.groovy # need cargo snapshots repo

install: mvn -B dependency:resolve dependency:resolve-plugins --settings ~/.m2/itSettings.xml
 
#before_script:
# - groovy script/travis/generateMavenSettingsForIT.groovy
  
script: mvn -version; mvn clean -B verify -P ${AS} --settings ~/.m2/itSettings.xml

notifications:
 email:
   - p6spy-developers@googlegroups.com