language: java

jdk:
  - oraclejdk7

before_install:
 - "sudo apt-get update -qq"

install: mvn dependency:resolve dependency:resolve-plugins
 

before_script:
 - groovy script/travis/generateMavenSettingsForIT.groovy
  
script: mvn -version; mvn clean install -P tomcat-6.x --settings ~/.m2/itSettings.xml

notifications:
 email: false
#   - p6spy-developers@googlegroups.com