language: java

jdk:
  - oraclejdk7

env:
  matrix:
    - AS=wildfly81x
    #- AS=jboss71x
    - AS=jboss61x
    - AS=jboss51x
    - AS=jboss42x
    - AS=glassfish4x
    - AS=glassfish31x
    
#before_install:
# - "sudo apt-get update -qq"
# - groovy script/travis/generateMavenSettingsForIT.groovy # need cargo snapshots repo

#install: mvn -B dependency:resolve dependency:resolve-plugins --settings ~/.m2/itSettings.xml
 
#before_script:
# - groovy script/travis/generateMavenSettingsForIT.groovy
  
#script: mvn -version; mvn clean -B verify -P ${AS} --settings ~/.m2/itSettings.xml
script: gradle clean unitTest -Pcontainer=${AS} --stacktrace

notifications:
 email:
   - p6spy-developers@googlegroups.com