language: java

jdk:
  - oraclejdk7

env:
  matrix:
    - AS=jonas-5.x
    
before_install:
 - "sudo apt-get update -qq"
 - groovy script/travis/generateMavenSettingsForIT.groovy # need cargo snapshots repo

install: mvn -B dependency:resolve dependency:resolve-plugins --settings ~/.m2/itSettings.xml
 
#before_script:
# - groovy script/travis/generateMavenSettingsForIT.groovy
  
script: mvn -version; mvn clean -B verify -P ${AS} --settings ~/.m2/itSettings.xml

notifications:
 email: false
#   - p6spy-developers@googlegroups.com