language: java

jdk:
  - oraclejdk7

env:
  matrix:
    - AS=wildfly81x
    #- AS=jboss71x
    - AS=jboss61x
    - AS=jboss51x
    - AS=jboss42x
    - AS=payara4x
    - AS=glassfish4x
    - AS=glassfish31x
    - AS=tomcat8x
    - AS=tomcat7x
    - AS=tomcat6x
    - AS=tomee16xweb
    - AS=tomee16xplus
    - AS=wls12x

before_install:
  - jdk_switcher use oraclejdk8
  - git clone https://github.com/felixbarny/p6spy.git
  - pushd p6spy
  - git checkout event-emitting-wrapper
  - mvn clean install -DskipTests=true
  - popd
  - jdk_switcher use oraclejdk7
  - export ORG_GRADLE_PROJECT_container=${AS}

script: ./gradlew unitTest --info
