language: java

jdk:
  - oraclejdk7

env:
  matrix:
    - AS=wildfly81x
    #- AS=jboss71x
    - AS=jboss61x
    - AS=jboss51x
    - AS=jboss42x
    - AS=glassfish4x
    - AS=glassfish31x
    
before_install:
  - export ORG_GRADLE_PROJECT_container=${AS}
# - "sudo apt-get update -qq"

script: ./gradlew unitTest --stacktrace

notifications:
 email:
   - p6spy-developers@googlegroups.com